In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        'Name': ['Rasel', 'Ali', np.nan, 'Ahmed', 'Mahmud'], # np.nan means emtpty value
        'Age': [25,26,np.nan,27,22],
        'Salary': [60000,52000,48000,np.nan,48000]
    }
)
df

     Name   Age   Salary
0   Rasel  25.0  60000.0
1     Ali  26.0  52000.0
2     NaN   NaN  48000.0
3   Ahmed  27.0      NaN
4  Mahmud  22.0  48000.0

In [ ]:
# if we want to remove the NaN value 
# But within 5 data 2 data drop is risky.
data = df.dropna()
data

     Name   Age   Salary
0   Rasel  25.0  60000.0
1     Ali  26.0  52000.0
4  Mahmud  22.0  48000.0

In [6]:
# So we will fill the NaN values.
data = df.fillna(
    {
        'Name': 'Unknown', # ba jekono nam use korte pari
        'Age': df['Age'].mean(),
        'Salary': 0 # ba mean salary dite pari
    }
)
data

      Name   Age   Salary
0    Rasel  25.0  60000.0
1      Ali  26.0  52000.0
2  Unknown  25.0  48000.0
3    Ahmed  27.0      0.0
4   Mahmud  22.0  48000.0

In [8]:
# Age column ke integer e convert korte.
data['Age'] = data['Age'].astype(int)
data

      Name  Age   Salary
0    Rasel   25  60000.0
1      Ali   26  52000.0
2  Unknown   25  48000.0
3    Ahmed   27      0.0
4   Mahmud   22  48000.0

In [ ]:
# We use 2D matrix for image training. like CNN.

np_array = np.array([[1,2,3],[4,5,6]]) # this is 2D array(list within list)
print(np_array)

[[1 2 3]
 [4 5 6]]

In [10]:
# Some other model uses 1D matrix for training. So we need reshape the matrix
reshape_array = np_array.reshape(3,2)
print(reshape_array)

[[1 2]
 [3 4]
 [5 6]]

In [11]:
# But reshape korar somoy row*col = value jeta oi hisebe reshpaing korte hobe.
# Like, original (3,2) = 6 so reshaping could possible to (6,1), (2,3), (1,6) and so on.
reshape_array = np_array.reshape(1,6)
print(reshape_array)

[[1 2 3 4 5 6]]

In [18]:
# Sometimes we have to join two matrix.
# If we join row wise then it call v_stack

a = np.array([[1,2,3],[4,5,4]])
b = np.array([[6,7,8],[9,10,11]])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 4]])

In [20]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:


# But join korar somoy kheyal rakhte hobe jeno column size same thake 2tar e.
v_stacked = np.vstack([a,b])
print(v_stacked)

[[ 1  2  3]
 [ 4  5  4]
 [ 6  7  8]
 [ 9 10 11]]

In [16]:
# Horizontal stacking e column thik thake but row add hoye jai
h_stacked = np.hstack([a,b])
print(h_stacked)

[[ 1  2  3  6  7  8]
 [ 4  5  4  9 10 11]]

In [21]:
# d stack or depthwise stack e 2ta matrix er e row and column same hoyte hoy.
# 1st matrix er (1,1) er value and 2nd matrix er (1,1) er value mile ekta row hoy evabe.
# ekta 3D matrix create hoy.

d_stacked = np.dstack([a,b])
print(d_stacked)

[[[ 1  6]
  [ 2  7]
  [ 3  8]]

 [[ 4  9]
  [ 5 10]
  [ 4 11]]]

In [22]:
# Splitting a big array
big_array = np.arange(10)
big_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
split_array = np.split(big_array,5) # 5 vage split korechi. equal number of split hote hobe.
print(split_array)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
# we can sort by a column

sorted_data = data.sort_values(by = 'Salary') # salary er upor base kore ascending order e sort korechi.
sorted_data

      Name  Age   Salary
3    Ahmed   27      0.0
2  Unknown   25  48000.0
4   Mahmud   22  48000.0
1      Ali   26  52000.0
0    Rasel   25  60000.0

In [ ]:
sorted_data = data.sort_values(by='Salary',ascending=False) # descending order e sorted.    
sorted_data

      Name  Age   Salary
0    Rasel   25  60000.0
1      Ali   26  52000.0
2  Unknown   25  48000.0
4   Mahmud   22  48000.0
3    Ahmed   27      0.0

In [31]:
# We can sort array.
array = np.array([1,2,3,43,21])
array

array([ 1,  2,  3, 43, 21])

In [32]:
print(np.sort(array))

[ 1  2  3 21 43]

In [ ]:
print(np.sort(array)[::-1]) # for descending order sorting

[43 21  3  2  1]

In [37]:
arr = np.array(['Rasel','Ali','Mahmud','Apple'])
print(np.sort(arr))

['Ali' 'Apple' 'Mahmud' 'Rasel']