In [16]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        'A': [21, np.nan, 22, 4, np.nan],
        'B': [31, 32, 33, 34, 35],
        'C': [np.nan, np.nan, np.nan, np.nan, np.nan],
        'D': [46, 47, np.nan, 48, 49]
    }
)
display(df)

# For count total NaN values
def count_nan(df):
    return df.isna().sum().sum()

print(f"Total NaN: {count_nan(df)}")

# Forward fill
df_ffill = df.ffill()
display(df_ffill)

# Backwad fill
df_bfill = df.bfill()
display(df_bfill)

# Fill with 0
df_zero = df.fillna(0)
display(df_zero)

      A   B   C     D
0  21.0  31 NaN  46.0
1   NaN  32 NaN  47.0
2  22.0  33 NaN   NaN
3   4.0  34 NaN  48.0
4   NaN  35 NaN  49.0

Total NaN: 8

      A   B   C     D
0  21.0  31 NaN  46.0
1  21.0  32 NaN  47.0
2  22.0  33 NaN  47.0
3   4.0  34 NaN  48.0
4   4.0  35 NaN  49.0

      A   B   C     D
0  21.0  31 NaN  46.0
1  22.0  32 NaN  47.0
2  22.0  33 NaN  48.0
3   4.0  34 NaN  48.0
4   NaN  35 NaN  49.0

      A   B    C     D
0  21.0  31  0.0  46.0
1   0.0  32  0.0  47.0
2  22.0  33  0.0   0.0
3   4.0  34  0.0  48.0
4   0.0  35  0.0  49.0