In [26]:
# A Pandas DataFrame is a two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns).
# Mainly csv file theke data read kore dataframe e rekhe kaj kori but ajke amra nijera ekta dictionary create kore then kaj korbo.

import pandas as pd
data = {
    'Name' : ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age' : [12, 4, 5],
    'Bamboo_Eat_Daily': [45, 53, 12]
}

df = pd.DataFrame(data)
print(df)

     Name  Age  Bamboo_Eat_Daily
0   Pandy   12                45
1  Bamboo    4                53
2   Fuzzy    5                12

In [13]:
# Let age 6 bochor ba tar kom jader tader data gula dekhbo, so ekhn filtering korte hobe.
df[df['Age']<=6] # mane df er data ta filtering kortechi and [er moddher ta holo condition] . evabe column er upor filtering korte hoy.

     Name  Age  Bamboo_Eat_Daily
1  Bamboo    4                53
2   Fuzzy    5                12

In [14]:
df[df['Name']=='Bamboo'] # only jader nam bamboo tader ta dekhabe.

     Name  Age  Bamboo_Eat_Daily
1  Bamboo    4                53

In [27]:
# creating new column with values
df['Job'] = ['Intern', 'Manager', 'CTO']
df

     Name  Age  Bamboo_Eat_Daily      Job
0   Pandy   12                45   Intern
1  Bamboo    4                53  Manager
2   Fuzzy    5                12      CTO

In [29]:
df['Sleep'] = [8,12,14]
df

     Name  Age  Bamboo_Eat_Daily      Job  Sleep
0   Pandy   12                45   Intern      8
1  Bamboo    4                53  Manager     12
2   Fuzzy    5                12      CTO     14

In [ ]:
# drop a column
df.drop('Bamboo_Eat_Daily', axis=1) # axis=1 mane column borabor and axis=0 mane row borabor khujbe.

     Name  Age      Job
0   Pandy   12   Intern
1  Bamboo    4  Manager
2   Fuzzy    5      CTO

In [18]:
# egula sob e virtually hocche. original df kintu same e ache change hoynai.
df

     Name  Age  Bamboo_Eat_Daily      Job
0   Pandy   12                45   Intern
1  Bamboo    4                53  Manager
2   Fuzzy    5                12      CTO

In [ ]:
# Jodi actually kono row ba column delete korte chai then:
df = df.drop('Bamboo_Eat_Daily', axis=1)

In [22]:
df

     Name  Age      Job
0   Pandy   12   Intern
1  Bamboo    4  Manager
2   Fuzzy    5      CTO

In [ ]:
# If wanted to delete a row
df = df.drop(0,axis=0) # 0 number row deleted. axis=0 karon row niye kaj korchi

In [30]:
df

     Name  Age  Bamboo_Eat_Daily      Job  Sleep
0   Pandy   12                45   Intern      8
1  Bamboo    4                53  Manager     12
2   Fuzzy    5                12      CTO     14

In [31]:
# If we want to drop multiple column
df = df.drop(['Bamboo_Eat_Daily', 'Sleep'], axis=1)
df

     Name  Age      Job
0   Pandy   12   Intern
1  Bamboo    4  Manager
2   Fuzzy    5      CTO

In [42]:
# Ekhn for security purpose row er indexing ta jodi manually korte chai tokhon.
data2 = {
    'Name' : ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age' : [12, 4, 5],
    'Bamboo_Eat_Daily': [45, 53, 12]
}

df2 = pd.DataFrame(data2, index=['a','b','c'])
print(df)

     Name  Age  Bamboo_Eat_Daily
a   Pandy   12                45
b  Bamboo    4                53
c   Fuzzy    5                12

In [43]:
# finding using used indexing number.
df2.loc['a']

Name                Pandy
Age                    12
Bamboo_Eat_Daily       45
Name: a, dtype: object

In [ ]:
# jodi index diye khujte chai taile:
df2.iloc[0] # 0 number index er column tar value dekhabe

Name                Pandy
Age                    12
Bamboo_Eat_Daily       45
Name: a, dtype: object

In [49]:
# let name and age dekhte cacchi a ar c column er.
df2.loc[['a','c'], ['Name', 'Age']]

    Name  Age
a  Pandy   12
c  Fuzzy    5

In [51]:
# if we want to see name and age only
df2[['Name','Age']]

     Name  Age
a   Pandy   12
b  Bamboo    4
c   Fuzzy    5

In [ ]:
# iloc use koreo korte pari
df2.iloc[[0,2],[0,1]] # Mane iloc dile integer use kore filtering korte parbo and only loc dile actual name dite hobe.

    Name  Age
a  Pandy   12
c  Fuzzy    5

In [ ]:
# To save something in csv format
df2.to_csv('output.csv')

In [56]:
# if we dont want the row numbering then 
df2.to_csv('output.csv', index=False)

In [ ]:
# if we want to save as excel then
#df2.to_excel('output.xlsx', index=False)

In [69]:
# to save as json format
df2.to_json('output.json')

In [70]:
df2

     Name  Age  Bamboo_Eat_Daily
a   Pandy   12                45
b  Bamboo    4                53
c   Fuzzy    5                12

In [72]:
# Multiple condition dite hole
df2[(df2['Age']<6) & (df2['Bamboo_Eat_Daily']>20)]

     Name  Age  Bamboo_Eat_Daily
b  Bamboo    4                53

In [76]:
# Left,right join on dataframe

left = pd.DataFrame(
    {
        'ID': [1, 2, 3],
        'Name': ['Bamboo', 'Fuzzy', 'Pandy']
    }
)

right = pd.DataFrame(
    {
        'ID': [1, 2, 4],
        'Hobby': ['Sleeping', 'Eating', 'Sitting']
    }
)

merged = pd.merge(left, right, on= 'ID', how='right') # kiser upor join korbo eta on e dite hobe and kivabe join korchi left na right seta how e dite hobe
merged

   ID    Name     Hobby
0   1  Bamboo  Sleeping
1   2   Fuzzy    Eating
2   4     NaN   Sitting